server:
  port: "${SERVER_PORT:8080}"
spring:
  application:
    name: "${APP_NAME:autenticacion}"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui"
    try-it-out-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    co.com.pragma.crediya.r2dbc.TokenSesionReactiveRepositoryAdapter: "DEBUG"
    org.springframework.r2dbc.core: "WARN"
    io.r2dbc.postgresql: "WARN"
cors:
  allowed-origins: "${ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}"
routes:
  paths:
    usuarios: "/api/v1/usuarios"
    login: "/api/v1/login"
adapters:
  r2dbc:
    host: "${SPRING_R2DBC_URL}"
    port: "${SPRING_R2DBC_PORT}"
    database: "${SPRING_R2DBC_DB_NAME}"
    schema: "${SPRING_R2DBC_SCHEMA}"
    username: "${SPRING_R2DBC_USERNAME}"
    password: "${SPRING_R2DBC_PASSWORD}"

