BEGIN;

-- Crea el esquema si no existe
CREATE SCHEMA IF NOT EXISTS crediya;

-- Tabla de roles
CREATE TABLE IF NOT EXISTS crediya.rol (
    id_rol      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL
);

-- Tabla de usuarios
CREATE TABLE IF NOT EXISTS crediya.usuario (
    id_usuario          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres             VARCHAR(255) NOT NULL,
    apellidos           VARCHAR(255) NOT NULL,
    documento_identidad VARCHAR(255),
    fecha_nacimiento    TIMESTAMP WITHOUT TIME ZONE,
    direccion           VARCHAR(255),
    telefono            VARCHAR(255),
    id_rol              BIGINT NOT NULL,
    correo_electronico  VARCHAR(255) NOT NULL,
    salario_base        DOUBLE PRECISION NOT NULL,

    CONSTRAINT uq_usuario_correo UNIQUE (correo_electronico),
    CONSTRAINT ck_usuario_salario CHECK (salario_base >= 0 AND salario_base <= 15000000),
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol) REFERENCES crediya.rol (id_rol)
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

-- Inserción de roles
INSERT INTO crediya.rol (nombre, descripcion) VALUES
  ('ADMINISTRADOR', 'Acceso total al sistema'),
  ('CLIENTE', 'Acceso estándar'),
  ('ASESOR', 'Gestión de solicitudes');

-- Tabla de permisos
CREATE TABLE IF NOT EXISTS crediya.permisos (
  id_permisos   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo        TEXT NOT NULL,
  nombre        TEXT NOT NULL,
  descripcion   TEXT,
  indhabilitado BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uq_permisos_codigo UNIQUE (codigo)
);

-- Tabla de credenciales
CREATE TABLE IF NOT EXISTS crediya.credenciales (
  id_credenciales   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario        BIGINT NOT NULL,
  correo_electronico TEXT NOT NULL,
  clave             TEXT NOT NULL,
  CONSTRAINT uq_credenciales_correo UNIQUE (correo_electronico),
  CONSTRAINT fk_credenciales_usuario
      FOREIGN KEY (id_usuario) REFERENCES crediya.usuario (id_usuario)
      ON UPDATE CASCADE ON DELETE CASCADE
);

-- Tabla rol_permisos
CREATE TABLE IF NOT EXISTS crediya.rol_permisos (
  id_rol_permisos BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol          BIGINT NOT NULL,
  id_permisos     BIGINT NOT NULL,
  indhabilitado   BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uq_rol_permisos UNIQUE (id_rol, id_permisos),
  CONSTRAINT fk_rol_permisos_rol
      FOREIGN KEY (id_rol) REFERENCES crediya.rol (id_rol)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_rol_permisos_permiso
      FOREIGN KEY (id_permisos) REFERENCES crediya.permisos (id_permisos)
      ON UPDATE CASCADE ON DELETE CASCADE
);

-- Tabla de tokens de sesión
CREATE TABLE IF NOT EXISTS crediya.token_sesion (
  id_token_sesion  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario       BIGINT NOT NULL,
  token            TEXT   NOT NULL,
  fecha_creacion   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  fecha_expiracion TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  indactivo        BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_token_sesion_usuario
      FOREIGN KEY (id_usuario) REFERENCES crediya.usuario (id_usuario)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_token_sesion_token UNIQUE (token)
);

-- Alter credenciales para seguridad
ALTER TABLE crediya.credenciales
  ADD COLUMN IF NOT EXISTS intentos_fallidos INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bloqueado        BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS fecha_bloqueo    TIMESTAMP;

-- Inserción de usuario
INSERT INTO crediya.usuario (
    id_usuario, nombres, apellidos, documento_identidad, fecha_nacimiento,
    direccion, telefono, id_rol, correo_electronico, salario_base
) VALUES (
    1,
    'Barbara',
    'Sepulveda',
    '098765431',
    '1995-11-02 19:00:00',
    'Calle 45 #20-15, Medellín',
    '+57 3109876543',
    1,
    'barbara.sepulveda@example.com',
    1500000
);

-- Inserción de credenciales
INSERT INTO crediya.credenciales (
    id_credenciales, id_usuario, correo_electronico, clave, intentos_fallidos, bloqueado
) VALUES (
    1,
    1,
    'barbara.sepulveda@example.com',
    '$2a$10$rvbuplWCBRIBzIKlDUvZuO2TNRmmwzNscfbj1NJwzNiO9tIm7HBKq',
    0,
    false
);

-- Inserción de permisos
INSERT INTO crediya.permisos (
    id_permisos, codigo, nombre, descripcion, indhabilitado
) VALUES
    (1, 'CREAR_USUARIO', 'Crear usuario', 'Permite registrar nuevos usuarios. Debe estar asignado a ADMIN y ASESOR.', true),
    (2, 'CREAR_SOLICITUD', 'Crear solicitud de préstamo', 'Permite a un CLIENTE crear solicitudes de préstamo. La validación de que sea para sí mismo se hace en el caso de uso.', true),
    (3, 'GESTIONAR_SOLICITUD', 'Gestionar solicitud de préstamo', 'Permite a un ASESOR gestionar solicitudes de préstamo.', true);

-- Inserción de rol_permisos
INSERT INTO crediya.rol_permisos (
    id_rol_permisos, id_rol, id_permisos, indhabilitado
) VALUES
    (1, 1, 1, true),
    (2, 3, 1, true),
    (3, 2, 2, true),
    (4, 3, 3, true);

COMMIT;